from app.models import Beach
from pydantic import BaseModel
from datetime import date

# Nearest NDBC buoy station IDs for reference
# 45007 = South Lake Michigan (seasonal — offline in winter)
# 45002 = North Lake Michigan
# 45008 = South Lake Huron
# 45005 = West Lake Erie
# 45006 = West Lake Superior (seasonal — offline in winter)
# 45024 = East Lake Michigan (near Grand Haven)
# 45214 = Lake Erie (near Detroit)
# HRBM4 = Harbor Beach, Lake Huron (reports water temp)

sample_beaches = [
    {
        "id": 1,
        "name": "Belle Isle Beach",
        "county": "Wayne",
        "latitude": 42.3416,
        "longitude": -82.9625,
        "lake": "Detroit River",
        "buoyStation": "45214",
        "status": "Safe",
        "countryCode": "US",
        "year": date.today().year,
        "parkType": "city_beach",
        "isSwimmable": True,
        "bodyOfWater": "Detroit River",
        "hasRestrooms": True,
        "hasCamping": False
    },
    {
        "id": 2,
        "name": "Grand Haven State Park",
        "county": "Ottawa",
        "latitude": 43.0564,
        "longitude": -86.2545,
        "lake": "Lake Michigan",
        "buoyStation": "45024",
        "status": "Advisory",
        "countryCode": "US",
        "year": date.today().year,
        "parkType": "state_park",
        "isSwimmable": True,
        "bodyOfWater": "Lake Michigan",
        "hasRestrooms": True,
        "hasCamping": True
    },
    {
        "id": 3,
        "name": "Silver Lake Beach",
        "county": "Oceana",
        "latitude": 43.6753,
        "longitude": -86.5214,
        "lake": "Lake Michigan",
        "buoyStation": "45024",
        "status": "Safe",
        "countryCode": "US",
        "year": date.today().year,
        "parkType": "state_park",
        "isSwimmable": True,
        "bodyOfWater": "Lake Michigan",
        "hasRestrooms": True,
        "hasCamping": True
    },
    {
        "id": 4,
        "name": "Sleeping Bear Dunes",
        "county": "Leelanau",
        "latitude": 44.8779,
        "longitude": -86.0590,
        "lake": "Lake Michigan",
        "buoyStation": "45002",
        "status": "Safe",
        "countryCode": "US",
        "year": date.today().year,
        "parkType": "national_park",
        "isSwimmable": True,
        "bodyOfWater": "Lake Michigan",
        "hasRestrooms": True,
        "hasCamping": True
    },
    {
        "id": 5,
        "name": "Tawas Point State Park",
        "county": "Iosco",
        "latitude": 44.2572,
        "longitude": -83.4467,
        "lake": "Lake Huron",
        "buoyStation": "45008",
        "status": "Safe",
        "countryCode": "US",
        "year": date.today().year,
        "parkType": "state_park",
        "isSwimmable": True,
        "bodyOfWater": "Lake Huron",
        "hasRestrooms": True,
        "hasCamping": True
    },
    {
        "id": 6,
        "name": "Holland State Park",
        "county": "Ottawa",
        "latitude": 42.7789,
        "longitude": -86.2048,
        "lake": "Lake Michigan",
        "buoyStation": "45024",
        "status": "Safe",
        "countryCode": "US",
        "year": date.today().year,
        "parkType": "state_park",
        "isSwimmable": True,
        "bodyOfWater": "Lake Michigan",
        "hasRestrooms": True,
        "hasCamping": True
    },
    {
        "id": 7,
        "name": "Ludington State Park",
        "county": "Mason",
        "latitude": 44.0349,
        "longitude": -86.5018,
        "lake": "Lake Michigan",
        "buoyStation": "45024",
        "status": "Safe",
        "countryCode": "US",
        "year": date.today().year,
        "parkType": "state_park",
        "isSwimmable": True,
        "bodyOfWater": "Lake Michigan",
        "hasRestrooms": True,
        "hasCamping": True
    },
    {
        "id": 8,
        "name": "P.J. Hoffmaster State Park",
        "county": "Muskegon",
        "latitude": 43.1329,
        "longitude": -86.2654,
        "lake": "Lake Michigan",
        "buoyStation": "45024",
        "status": "Safe",
        "countryCode": "US",
        "year": date.today().year,
        "parkType": "state_park",
        "isSwimmable": True,
        "bodyOfWater": "Lake Michigan",
        "hasRestrooms": True,
        "hasCamping": True
    },
    {
        "id": 9,
        "name": "Warren Dunes State Park",
        "county": "Berrien",
        "latitude": 41.9153,
        "longitude": -86.5934,
        "lake": "Lake Michigan",
        "buoyStation": "45007",
        "status": "Safe",
        "countryCode": "US",
        "year": date.today().year,
        "parkType": "state_park",
        "isSwimmable": True,
        "bodyOfWater": "Lake Michigan",
        "hasRestrooms": True,
        "hasCamping": True
    },
    {
        "id": 10,
        "name": "Petoskey State Park",
        "county": "Emmet",
        "latitude": 45.4068,
        "longitude": -84.9086,
        "lake": "Lake Michigan",
        "buoyStation": "45002",
        "status": "Safe",
        "countryCode": "US",
        "year": date.today().year,
        "parkType": "state_park",
        "isSwimmable": True,
        "bodyOfWater": "Lake Michigan",
        "hasRestrooms": True,
        "hasCamping": True
    },
    {
        "id": 11,
        "name": "Pictured Rocks National Lakeshore",
        "county": "Alger",
        "latitude": 46.5643,
        "longitude": -86.3163,
        "lake": "Lake Superior",
        "buoyStation": "45006",
        "status": "Safe",
        "countryCode": "US",
        "year": date.today().year,
        "parkType": "national_park",
        "isSwimmable": False,
        "bodyOfWater": "Lake Superior",
        "hasRestrooms": True,
        "hasCamping": True
    },
    {
        "id": 12,
        "name": "Presque Isle Park",
        "county": "Marquette",
        "latitude": 46.5880,
        "longitude": -87.3818,
        "lake": "Lake Superior",
        "buoyStation": "45006",
        "status": "Safe",
        "countryCode": "US",
        "year": date.today().year,
        "parkType": "city_beach",
        "isSwimmable": False,
        "bodyOfWater": "Lake Superior",
        "hasRestrooms": True,
        "hasCamping": False
    },
    {
        "id": 13,
        "name": "Harrisville State Park",
        "county": "Alcona",
        "latitude": 44.6475,
        "longitude": -83.2976,
        "lake": "Lake Huron",
        "buoyStation": "45008",
        "status": "Safe",
        "countryCode": "US",
        "year": date.today().year,
        "parkType": "state_park",
        "isSwimmable": True,
        "bodyOfWater": "Lake Huron",
        "hasRestrooms": True,
        "hasCamping": True
    },
    {
        "id": 14,
        "name": "Sterling State Park",
        "county": "Monroe",
        "latitude": 41.9200,
        "longitude": -83.3415,
        "lake": "Lake Erie",
        "buoyStation": "45214",
        "status": "Safe",
        "countryCode": "US",
        "year": date.today().year,
        "parkType": "state_park",
        "isSwimmable": True,
        "bodyOfWater": "Lake Erie",
        "hasRestrooms": True,
        "hasCamping": True
    },
    {
        "id": 15,
        "name": "Muskegon State Park",
        "county": "Muskegon",
        "latitude": 43.2485,
        "longitude": -86.3339,
        "lake": "Lake Michigan",
        "buoyStation": "45024",
        "status": "Safe",
        "countryCode": "US",
        "year": date.today().year,
        "parkType": "state_park",
        "isSwimmable": True,
        "bodyOfWater": "Lake Michigan",
        "hasRestrooms": True,
        "hasCamping": True
    },
    {
        "id": 16,
        "name": "Saugatuck Dunes State Park",
        "county": "Allegan",
        "latitude": 42.6968,
        "longitude": -86.1903,
        "lake": "Lake Michigan",
        "buoyStation": "45024",
        "status": "Safe",
        "countryCode": "US",
        "year": date.today().year,
        "parkType": "state_park",
        "isSwimmable": True,
        "bodyOfWater": "Lake Michigan",
        "hasRestrooms": True,
        "hasCamping": False
    },
    {
        "id": 17,
        "name": "South Haven South Beach",
        "county": "Van Buren",
        "latitude": 42.4031,
        "longitude": -86.2736,
        "lake": "Lake Michigan",
        "buoyStation": "45024",
        "status": "Safe",
        "countryCode": "US",
        "year": date.today().year,
        "parkType": "city_beach",
        "isSwimmable": True,
        "bodyOfWater": "Lake Michigan",
        "hasRestrooms": True,
        "hasCamping": False
    },
    {
        "id": 18,
        "name": "Port Crescent State Park",
        "county": "Huron",
        "latitude": 44.0103,
        "longitude": -83.0508,
        "lake": "Lake Huron",
        "buoyStation": "45008",
        "status": "Safe",
        "countryCode": "US",
        "year": date.today().year,
        "parkType": "state_park",
        "isSwimmable": True,
        "bodyOfWater": "Lake Huron",
        "hasRestrooms": True,
        "hasCamping": True
    },
    {
        "id": 19,
        "name": "Albert E. Sleeper State Park",
        "county": "Huron",
        "latitude": 43.9726,
        "longitude": -83.2055,
        "lake": "Lake Huron",
        "buoyStation": "45008",
        "status": "Safe",
        "countryCode": "US",
        "year": date.today().year,
        "parkType": "state_park",
        "isSwimmable": True,
        "bodyOfWater": "Lake Huron",
        "hasRestrooms": True,
        "hasCamping": True
    },
    {
        "id": 20,
        "name": "McLain State Park",
        "county": "Houghton",
        "latitude": 47.2371,
        "longitude": -88.6088,
        "lake": "Lake Superior",
        "buoyStation": "45006",
        "status": "Safe",
        "countryCode": "US",
        "year": date.today().year,
        "parkType": "state_park",
        "isSwimmable": True,
        "bodyOfWater": "Lake Superior",
        "hasRestrooms": True,
        "hasCamping": True
    },
    {
        "id": 21,
        "name": "Porcupine Mountains Wilderness State Park",
        "county": "Ontonagon",
        "latitude": 46.7811,
        "longitude": -89.6807,
        "lake": "Lake Superior",
        "buoyStation": "45006",
        "status": "Safe",
        "countryCode": "US",
        "year": date.today().year,
        "parkType": "state_park",
        "isSwimmable": True,
        "bodyOfWater": "Lake Superior",
        "hasRestrooms": True,
        "hasCamping": True
    },
    {
        "id": 22,
        "name": "Traverse City State Park",
        "county": "Grand Traverse",
        "latitude": 44.7354,
        "longitude": -85.5771,
        "lake": "Lake Michigan",
        "buoyStation": "45024",
        "status": "Safe",
        "countryCode": "US",
        "year": date.today().year,
        "parkType": "state_park",
        "isSwimmable": True,
        "bodyOfWater": "Lake Michigan",
        "hasRestrooms": True,
        "hasCamping": True
    },
    {
        "id": 23,
        "name": "Nordhouse Dunes",
        "county": "Mason",
        "latitude": 43.9500,
        "longitude": -86.4800,
        "lake": "Lake Michigan",
        "buoyStation": "45024",
        "status": "Safe",
        "countryCode": "US",
        "year": date.today().year,
        "parkType": "wilderness_area",
        "isSwimmable": True,
        "bodyOfWater": "Lake Michigan",
        "hasRestrooms": False,
        "hasCamping": True
    },
    {
        "id": 24,
        "name": "Harbor Beach",
        "county": "Huron",
        "latitude": 43.8439,
        "longitude": -82.6513,
        "lake": "Lake Huron",
        "buoyStation": "HRBM4",
        "status": "Safe",
        "countryCode": "US",
        "year": date.today().year,
        "parkType": "city_beach",
        "isSwimmable": True,
        "bodyOfWater": "Lake Huron",
        "hasRestrooms": True,
        "hasCamping": False
    },
    {
        "id": 25,
        "name": "Fort Wilkins State Park",
        "county": "Keweenaw",
        "latitude": 47.4658,
        "longitude": -87.8823,
        "lake": "Lake Superior",
        "buoyStation": "45006",
        "status": "Safe",
        "countryCode": "US",
        "year": date.today().year,
        "parkType": "state_park",
        "isSwimmable": True,
        "bodyOfWater": "Lake Superior",
        "hasRestrooms": True,
        "hasCamping": True
    },
    {
        "id": 26,
        "name": "Grand Marais Beach",
        "county": "Alger",
        "latitude": 46.6741,
        "longitude": -85.9766,
        "lake": "Lake Superior",
        "buoyStation": "45006",
        "status": "Safe",
        "countryCode": "US",
        "year": date.today().year,
        "parkType": "city_beach",
        "isSwimmable": True,
        "bodyOfWater": "Lake Superior",
        "hasRestrooms": True,
        "hasCamping": False
    },
    {
        "id": 27,
        "name": "Oval Beach",
        "county": "Allegan",
        "latitude": 42.6543,
        "longitude": -86.2196,
        "lake": "Lake Michigan",
        "buoyStation": "45024",
        "status": "Safe",
        "countryCode": "US",
        "year": date.today().year,
        "parkType": "city_beach",
        "isSwimmable": True,
        "bodyOfWater": "Lake Michigan",
        "hasRestrooms": True,
        "hasCamping": False
    },
    {
        "id": 28,
        "name": "Tunnel Park",
        "county": "Ottawa",
        "latitude": 42.7654,
        "longitude": -86.2198,
        "lake": "Lake Michigan",
        "buoyStation": "45024",
        "status": "Safe",
        "countryCode": "US",
        "year": date.today().year,
        "parkType": "county_park",
        "isSwimmable": True,
        "bodyOfWater": "Lake Michigan",
        "hasRestrooms": True,
        "hasCamping": False
    },
    {
        "id": 29,
        "name": "Pere Marquette Beach",
        "county": "Muskegon",
        "latitude": 43.2317,
        "longitude": -86.3539,
        "lake": "Lake Michigan",
        "buoyStation": "45024",
        "status": "Safe",
        "countryCode": "US",
        "year": date.today().year,
        "parkType": "city_beach",
        "isSwimmable": True,
        "bodyOfWater": "Lake Michigan",
        "hasRestrooms": True,
        "hasCamping": False
    },
    {
        "id": 30,
        "name": "North Beach Park",
        "county": "Ottawa",
        "latitude": 43.0731,
        "longitude": -86.2567,
        "lake": "Lake Michigan",
        "buoyStation": "45024",
        "status": "Safe",
        "countryCode": "US",
        "year": date.today().year,
        "parkType": "county_park",
        "isSwimmable": True,
        "bodyOfWater": "Lake Michigan",
        "hasRestrooms": True,
        "hasCamping": False
    },
    {
        "id": 31,
        "name": "Kirk Park",
        "county": "Ottawa",
        "latitude": 42.9920,
        "longitude": -86.2534,
        "lake": "Lake Michigan",
        "buoyStation": "45024",
        "status": "Safe",
        "countryCode": "US",
        "year": date.today().year,
        "parkType": "county_park",
        "isSwimmable": True,
        "bodyOfWater": "Lake Michigan",
        "hasRestrooms": True,
        "hasCamping": False
    },
    {
        "id": 32,
        "name": "Caseville County Park",
        "county": "Huron",
        "latitude": 43.9414,
        "longitude": -83.2716,
        "lake": "Lake Huron",
        "buoyStation": "45008",
        "status": "Safe",
        "countryCode": "US",
        "year": date.today().year,
        "parkType": "county_park",
        "isSwimmable": True,
        "bodyOfWater": "Lake Huron",
        "hasRestrooms": True,
        "hasCamping": True
    },
    {
        "id": 33,
        "name": "Lexington Beach",
        "county": "Sanilac",
        "latitude": 43.2654,
        "longitude": -82.5321,
        "lake": "Lake Huron",
        "buoyStation": "45008",
        "status": "Safe",
        "countryCode": "US",
        "year": date.today().year,
        "parkType": "city_beach",
        "isSwimmable": True,
        "bodyOfWater": "Lake Huron",
        "hasRestrooms": True,
        "hasCamping": False
    },
    {
        "id": 34,
        "name": "Oscoda Beach",
        "county": "Iosco",
        "latitude": 44.4317,
        "longitude": -83.3354,
        "lake": "Lake Huron",
        "buoyStation": "45008",
        "status": "Safe",
        "countryCode": "US",
        "year": date.today().year,
        "parkType": "city_beach",
        "isSwimmable": True,
        "bodyOfWater": "Lake Huron",
        "hasRestrooms": True,
        "hasCamping": False
    },
    {
        "id": 35,
        "name": "Agate Beach",
        "county": "Keweenaw",
        "latitude": 47.4679,
        "longitude": -87.8821,
        "lake": "Lake Superior",
        "buoyStation": "45006",
        "status": "Safe",
        "countryCode": "US",
        "year": date.today().year,
        "parkType": "city_beach",
        "isSwimmable": False,
        "bodyOfWater": "Lake Superior",
        "hasRestrooms": False,
        "hasCamping": False
    },
    {
        "id": 36,
        "name": "Ontonagon Beach",
        "county": "Ontonagon",
        "latitude": 46.8731,
        "longitude": -89.3217,
        "lake": "Lake Superior",
        "buoyStation": "45006",
        "status": "Safe",
        "countryCode": "US",
        "year": date.today().year,
        "parkType": "city_beach",
        "isSwimmable": True,
        "bodyOfWater": "Lake Superior",
        "hasRestrooms": True,
        "hasCamping": False
    },
    {
        "id": 37,
        "name": "Whitefish Point Beach",
        "county": "Chippewa",
        "latitude": 46.7698,
        "longitude": -84.9574,
        "lake": "Lake Superior",
        "buoyStation": "45006",
        "status": "Safe",
        "countryCode": "US",
        "year": date.today().year,
        "parkType": "wilderness_area",
        "isSwimmable": False,
        "bodyOfWater": "Lake Superior",
        "hasRestrooms": True,
        "hasCamping": False
    },
    {
        "id": 38,
        "name": "Munising Beach",
        "county": "Alger",
        "latitude": 46.4121,
        "longitude": -86.6554,
        "lake": "Lake Superior",
        "buoyStation": "45006",
        "status": "Safe",
        "countryCode": "US",
        "year": date.today().year,
        "parkType": "city_beach",
        "isSwimmable": True,
        "bodyOfWater": "Lake Superior",
        "hasRestrooms": True,
        "hasCamping": False
    },
    {
        "id": 39,
        "name": "Bay City State Park",
        "county": "Bay",
        "latitude": 43.6548,
        "longitude": -83.8967,
        "lake": "Lake Huron",
        "buoyStation": "45008",
        "status": "Safe",
        "countryCode": "US",
        "year": date.today().year,
        "parkType": "state_park",
        "isSwimmable": True,
        "bodyOfWater": "Lake Huron",
        "hasRestrooms": True,
        "hasCamping": True
    },
    {
        "id": 40,
        "name": "Lakeport State Park",
        "county": "St. Clair",
        "latitude": 43.1432,
        "longitude": -82.4987,
        "lake": "Lake Huron",
        "buoyStation": "45008",
        "status": "Safe",
        "countryCode": "US",
        "year": date.today().year,
        "parkType": "state_park",
        "isSwimmable": True,
        "bodyOfWater": "Lake Huron",
        "hasRestrooms": True,
        "hasCamping": True
    },
    {
        "id": 41,
        "name": "Cheboygan State Park",
        "county": "Cheboygan",
        "latitude": 45.6543,
        "longitude": -84.4732,
        "lake": "Lake Huron",
        "buoyStation": "45008",
        "status": "Safe",
        "countryCode": "US",
        "year": date.today().year,
        "parkType": "state_park",
        "isSwimmable": True,
        "bodyOfWater": "Lake Huron",
        "hasRestrooms": True,
        "hasCamping": True
    },
    {
        "id": 42,
        "name": "Hoeft State Park",
        "county": "Presque Isle",
        "latitude": 45.4321,
        "longitude": -83.9876,
        "lake": "Lake Huron",
        "buoyStation": "45008",
        "status": "Safe",
        "countryCode": "US",
        "year": date.today().year,
        "parkType": "state_park",
        "isSwimmable": True,
        "bodyOfWater": "Lake Huron",
        "hasRestrooms": True,
        "hasCamping": True
    },
    {
        "id": 43,
        "name": "Fisherman's Island State Park",
        "county": "Charlevoix",
        "latitude": 45.2876,
        "longitude": -85.2543,
        "lake": "Lake Michigan",
        "buoyStation": "45002",
        "status": "Safe",
        "countryCode": "US",
        "year": date.today().year,
        "parkType": "state_park",
        "isSwimmable": True,
        "bodyOfWater": "Lake Michigan",
        "hasRestrooms": True,
        "hasCamping": True
    },
    {
        "id": 44,
        "name": "Young State Park",
        "county": "Charlevoix",
        "latitude": 45.1987,
        "longitude": -85.2198,
        "lake": "Lake Michigan",
        "buoyStation": "45002",
        "status": "Safe",
        "countryCode": "US",
        "year": date.today().year,
        "parkType": "state_park",
        "isSwimmable": True,
        "bodyOfWater": "Lake Michigan",
        "hasRestrooms": True,
        "hasCamping": True
    },
    {
        "id": 45,
        "name": "Empire Beach",
        "county": "Leelanau",
        "latitude": 44.8123,
        "longitude": -86.0587,
        "lake": "Lake Michigan",
        "buoyStation": "45024",
        "status": "Safe",
        "countryCode": "US",
        "year": date.today().year,
        "parkType": "national_park",
        "isSwimmable": True,
        "bodyOfWater": "Lake Michigan",
        "hasRestrooms": True,
        "hasCamping": False
    },
    {
        "id": 46,
        "name": "Leland Beach",
        "county": "Leelanau",
        "latitude": 45.0234,
        "longitude": -85.7654,
        "lake": "Lake Michigan",
        "buoyStation": "45002",
        "status": "Safe",
        "countryCode": "US",
        "year": date.today().year,
        "parkType": "city_beach",
        "isSwimmable": True,
        "bodyOfWater": "Lake Michigan",
        "hasRestrooms": True,
        "hasCamping": False
    },
    {
        "id": 47,
        "name": "Frankfort Beach",
        "county": "Benzie",
        "latitude": 44.6321,
        "longitude": -86.2354,
        "lake": "Lake Michigan",
        "buoyStation": "45024",
        "status": "Safe",
        "countryCode": "US",
        "year": date.today().year,
        "parkType": "city_beach",
        "isSwimmable": True,
        "bodyOfWater": "Lake Michigan",
        "hasRestrooms": True,
        "hasCamping": False
    },
    {
        "id": 48,
        "name": "Arcadia Beach",
        "county": "Manistee",
        "latitude": 44.5123,
        "longitude": -86.2198,
        "lake": "Lake Michigan",
        "buoyStation": "45024",
        "status": "Safe",
        "countryCode": "US",
        "year": date.today().year,
        "parkType": "city_beach",
        "isSwimmable": True,
        "bodyOfWater": "Lake Michigan",
        "hasRestrooms": True,
        "hasCamping": False
    },
    {
        "id": 49,
        "name": "Manistee North Beach",
        "county": "Manistee",
        "latitude": 44.2543,
        "longitude": -86.3321,
        "lake": "Lake Michigan",
        "buoyStation": "45024",
        "status": "Safe",
        "countryCode": "US",
        "year": date.today().year,
        "parkType": "city_beach",
        "isSwimmable": True,
        "bodyOfWater": "Lake Michigan",
        "hasRestrooms": True,
        "hasCamping": False
    },
    {
        "id": 50,
        "name": "Pentwater Beach",
        "county": "Oceana",
        "latitude": 43.7832,
        "longitude": -86.4321,
        "lake": "Lake Michigan",
        "buoyStation": "45024",
        "status": "Safe",
        "countryCode": "US",
        "year": date.today().year,
        "parkType": "city_beach",
        "isSwimmable": True,
        "bodyOfWater": "Lake Michigan",
        "hasRestrooms": True,
        "hasCamping": False
    },
    {
        "id": 51,
        "name": "White Lake Beach",
        "county": "Muskegon",
        "latitude": 43.5987,
        "longitude": -86.3987,
        "lake": "Lake Michigan",
        "buoyStation": "45024",
        "status": "Safe",
        "countryCode": "US",
        "year": date.today().year,
        "parkType": "city_beach",
        "isSwimmable": True,
        "bodyOfWater": "Lake Michigan",
        "hasRestrooms": True,
        "hasCamping": False
    },
    {
        "id": 52,
        "name": "New Buffalo Beach",
        "county": "Berrien",
        "latitude": 41.7965,
        "longitude": -86.7432,
        "lake": "Lake Michigan",
        "buoyStation": "45007",
        "status": "Safe",
        "countryCode": "US",
        "year": date.today().year,
        "parkType": "city_beach",
        "isSwimmable": True,
        "bodyOfWater": "Lake Michigan",
        "hasRestrooms": True,
        "hasCamping": False
    },
    {
        "id": 53,
        "name": "St. Joseph Beach",
        "county": "Berrien",
        "latitude": 42.1098,
        "longitude": -86.4876,
        "lake": "Lake Michigan",
        "buoyStation": "45007",
        "status": "Safe",
        "countryCode": "US",
        "year": date.today().year,
        "parkType": "city_beach",
        "isSwimmable": True,
        "bodyOfWater": "Lake Michigan",
        "hasRestrooms": True,
        "hasCamping": False
    },
    {
        "id": 54,
        "name": "Lake Erie Metropark Beach",
        "county": "Wayne",
        "latitude": 42.0876,
        "longitude": -83.1987,
        "lake": "Lake Erie",
        "buoyStation": "45214",
        "status": "Safe",
        "countryCode": "US",
        "year": date.today().year,
        "parkType": "metropark",
        "isSwimmable": True,
        "bodyOfWater": "Lake Erie",
        "hasRestrooms": True,
        "hasCamping": False
    },
]